// components/editor/ToolBar.vue
<template>
  <div class="buttons">
    <b-button
      @click="editor.chain().focus().toggleBold().run()"
      :class="{ 'is-info': editor.isActive('bold') }"
      icon-right="format-bold"
      title="Bold"
    />
    <b-button
      @click="editor.chain().focus().toggleItalic().run()"
      :class="{ 'is-info': editor.isActive('italic') }"
      icon-right="format-italic"
      title="italic"
    />
    <b-button
      @click="editor.chain().focus().toggleStrike().run()"
      :class="{ 'is-info': editor.isActive('strike') }"
      icon-right="format-strikethrough"
      title="strikethrough"
    />

    <b-button
      @click="editor.chain().focus().toggleCode().run()"
      :class="{ 'is-info': editor.isActive('code') }"
      icon-right="code-tags"
      title="Inline code"
    />

    <b-button
      @click="editor.chain().focus().toggleCodeBlock().run()"
      :class="{ 'is-info': editor.isActive('codeBlock') }"
      icon-right="code-not-equal-variant"
      title="code block"
    />

    <b-button
      @click="clearFormat"
      icon-right="format-clear"
      title="remove inline formatting"
    />

    <b-button
      @click="editor.chain().focus().setParagraph().run()"
      :class="{
        'is-info': editor.isActive('paragraph'),
      }"
      label="P"
    />

    <b-button
      @click="toggleHeading(1)"
      :class="{ 'is-info': editor.isActive('heading', { level: 1 }) }"
      label="H1"
    />
    <b-button
      @click="toggleHeading(2)"
      :class="{ 'is-info': editor.isActive('heading', { level: 2 }) }"
      label="H2"
    />
    <b-button
      @click="toggleHeading(3)"
      :class="{ 'is-info': editor.isActive('heading', { level: 3 }) }"
      label="H3"
    />
    <b-button
      @click="toggleHeading(4)"
      :class="{ 'is-info': editor.isActive('heading', { level: 4 }) }"
      label="H4"
    />
    <b-button
      @click="toggleHeading(5)"
      :class="{ 'is-info': editor.isActive('heading', { level: 5 }) }"
      label="H5"
    />
    <b-button
      @click="toggleHeading(6)"
      :class="{ 'is-info': editor.isActive('heading', { level: 6 }) }"
      label="H6"
    />
    <b-button
      @click="editor.chain().focus().toggleBulletList().run()"
      :class="{ 'is-info': editor.isActive('bulletList') }"
      icon-right="format-list-bulleted"
      title="Bullet list"
    />
    <b-button
      @click="editor.chain().focus().toggleOrderedList().run()"
      :class="{ 'is-info': editor.isActive('orderedList') }"
      icon-right="format-list-numbered"
      title="Ordered list"
    />
    <b-button
      @click="editor.chain().focus().toggleBlockquote().run()"
      :class="{ 'is-info': editor.isActive('blockquote') }"
      icon-right="format-quote-close"
      title="Blockquote"
    />

    <b-button
      @click="editor.chain().focus().setHorizontalRule().run()"
      title="horizontal rule"
      label="---"
    />

    <b-button
      @click="editor.chain().focus().undo().run()"
      title="Undo"
      icon-right="undo"
    />
    <b-button
      @click="editor.chain().focus().redo().run()"
      title="Redo"
      icon-right="redo"
    />
    <b-button
      @click="showLibrary = true"
      icon-right="image"
      title="Insert image"
    />
    <b-button
      @click="buttonClicked('logOutput')"
      title="Show output in console"
      icon-right="console"
    />

    <b-modal
      v-model="showLibrary"
      has-modal-card
      full-screen
      trap-focus
      :destroy-on-hide="false"
      aria-role="dialog"
      aria-label="Media Library"
      close-button-aria-label="Close"
      aria-modal
    >
      <div class="modal-card">
        <header class="modal-card-head">
          <p class="modal-card-title has-text-dark">Media Library</p>
        </header>
        <section class="modal-card-body has-background-dark">
          <MediaLibrary @onSelect="onMediaSelect" />
        </section>
      </div>
    </b-modal>

    <b-modal
      v-model="showImageOptions"
      has-modal-card
      trap-focus
      :destroy-on-hide="false"
      aria-role="dialog"
      aria-label="Image Options"
      close-button-aria-label="Close"
      aria-modal
    >
      <ImageCard v-if="selectedFile" :image="selectedFile">
        <b-field label="Caption">
          <b-input
            type="textarea"
            v-model="images[selectedFile.data.id].caption"
          ></b-input>
        </b-field>
        <b-field label="Alt text">
          <b-input v-model="images[selectedFile.data.id].alt"></b-input>
        </b-field>
        <b-button
          type="is-primary"
          label="Insert"
          @click="onMediaInsert(selectedFile)"
        />
      </ImageCard>
    </b-modal>
  </div>
</template>

<script>
import MediaLibrary from "../media/MediaLibrary.vue";
import ImageCard from "../media/ImageCard.vue";

export default {
  name: "ToolBar",
  props: ["editor"],
  data() {
    return {
      showLibrary: false,
      showImageOptions: false,
      selectedFile: null,
      images: {},
    };
  },
  methods: {
    buttonClicked(eventName) {
      this.$emit(eventName);
    },
    clearFormat() {
      this.editor.chain().focus().unsetAllMarks().run();
      this.editor.chain().focus().clearNodes().run();
    },
    toggleHeading(level) {
      this.editor.chain().focus().toggleHeading({ level }).run();
    },
    onMediaSelect(media) {
      this.showImageOptions = true;
      if (!this.images[media.data.id]) {
        this.images[media.data.id] = {
          caption: "",
          alt: media.data.alt,
        };
      }
      this.selectedFile = media;
    },
    onMediaInsert(media) {
      const src = media.full;
      const { caption, alt } = this.images[media.data.id];
      const { id } = media.data;

      this.editor.commands.setImage({ src, alt, caption, id });
      this.showLibrary = false;
      this.showImageOptions = false;
    },
  },
  components: { MediaLibrary, ImageCard },
};
</script>

// src/app/dashboard/editor/toolbar/toolbar.component.ts
import { Component, Input } from '@angular/core';
import { Button, ButtonModule } from 'primeng/button';
import { Editor } from '@tiptap/core';
import { Level } from '@tiptap/extension-heading';
import { FontAwesomeModule } from '@fortawesome/angular-fontawesome';
import { Icons } from './toolbar.icons';
import { MediaService } from '../../../services/media.service';
import { DialogService, DynamicDialogModule } from 'primeng/dynamicdialog';
import { VideoInputComponent } from '../video-input/video-input.component';
import { Subscription } from 'rxjs';

@Component({
  selector: 'app-toolbar',
  standalone: true,
  imports: [ButtonModule, DynamicDialogModule, FontAwesomeModule],
  templateUrl: './toolbar.component.html',
  styleUrl: './toolbar.component.scss',
  providers: [DialogService]
})
export class ToolbarComponent {
  @Input({ required: true }) editor!: Editor;

  public headingLevels = [...Array(6).keys()].map((level) => level + 1 as Level);
  public icons = Icons;

  private subs: Subscription[] = [];

  constructor(private dialogService: DialogService, private media: MediaService) { }

  public get focus() {
    return this.editor.chain().focus();
  }

  public buttonSeverity(style: string, attributes?: {}): Button['severity'] {
    return this.editor.isActive(style, attributes) ? 'success' : undefined;
  }

  public logOutput(): void {
    console.log(this.editor.getJSON());
  }

  public showImageLibrary(): void {
    this.media.launchLibrary(this.dialogService);
  }

  public showVideoInput(): void {
    const ref = this.dialogService.open(VideoInputComponent, { header: 'Video URL' });
    this.subs.push(ref.onClose.subscribe(src => {
      this.editor.commands.setExternalVideo({ src });
    }));
  }

}

<div class="flex justify-content-center pb-3 flex-wrap">
  <p-button
    [severity]="buttonSeverity('bold')"
    title="Bold"
    icon="fa-solid fa-google"
    (onClick)="focus.toggleBold().run()"
  >
    <fa-icon [icon]="icons.bold"></fa-icon>
  </p-button>
  <p-button
    [severity]="buttonSeverity('italic')"
    title="Italic"
    (onClick)="focus.toggleItalic().run()"
  >
    <fa-icon [icon]="icons.italic"></fa-icon>
  </p-button>
  <p-button
    [severity]="buttonSeverity('strike')"
    title="Strikethrough"
    (onClick)="focus.toggleStrike().run()"
  >
    <fa-icon [icon]="icons.strikeThrough"></fa-icon>
  </p-button>

  <p-button
    [severity]="buttonSeverity('code')"
    title="Inline code"
    (onClick)="focus.toggleCode().run()"
  >
    <fa-icon [icon]="icons.codeInline"></fa-icon>
  </p-button>

  <p-button
    [severity]="buttonSeverity('codeBlock')"
    title="Code block"
    (onClick)="focus.toggleCodeBlock().run()"
  >
    <fa-icon [icon]="icons.codeBlock"></fa-icon>
  </p-button>

  <p-button
    title="Remove formatting"
    (onClick)="focus.unsetAllMarks().clearNodes().run()"
  >
    <fa-icon [icon]="icons.removeFormating"></fa-icon>
  </p-button>

  <p-button
    [severity]="buttonSeverity('paragraph')"
    title="Paragraph"
    (onClick)="focus.setParagraph().run()"
  >
    <fa-icon [icon]="icons.paragraph"></fa-icon>
  </p-button>

  @for (level of headingLevels; track level) {
    <p-button
      [severity]="buttonSeverity('heading', { level })"
      (onClick)="editor.chain().focus().setHeading({ level }).run()"
      title="H{{ level }}"
      >H{{ level }}</p-button
    >
  }
  <hr class="w-full m-0 opacity-0" />

  <p-button
    [severity]="buttonSeverity('columns')"
    title="Columned section"
    (onClick)="colInput.toggle($event)"
  >
    <fa-icon [icon]="icons.columns"></fa-icon>
  </p-button>

  <p-button
    [severity]="buttonSeverity('bulletList')"
    title="Bullet list"
    (onClick)="focus.toggleBulletList().run()"
  >
    <fa-icon [icon]="icons.bulletList"></fa-icon>
  </p-button>

  <p-button
    [severity]="buttonSeverity('orderedList')"
    title="Ordered list"
    (onClick)="focus.toggleOrderedList().run()"
  >
    <fa-icon [icon]="icons.orderedList"></fa-icon>
  </p-button>

  <p-button
    [severity]="buttonSeverity('blockquote')"
    title="Blockquote"
    (onClick)="focus.toggleBlockquote().run()"
  >
    <fa-icon [icon]="icons.blockQuote"></fa-icon>
  </p-button>

  <p-button title="Horizontal Rule" (onClick)="focus.setHorizontalRule().run()">
    ---
  </p-button>

  <p-button title="Undo" (onClick)="focus.undo().run()">
    <fa-icon [icon]="icons.undo"></fa-icon>
  </p-button>
  <p-button title="Redo" (onClick)="focus.redo().run()">
    <fa-icon [icon]="icons.redo"></fa-icon>
  </p-button>
  <p-button
    [severity]="buttonSeverity('link')"
    title="Link"
    (onClick)="showLinkInput()"
  >
    <fa-icon [icon]="icons.link"></fa-icon>
  </p-button>
  <p-button title="Insert image" (onClick)="showImageLibrary()">
    <fa-icon [icon]="icons.image"></fa-icon>
  </p-button>
  <p-button title="Insert video" (onClick)="showVideoInput()">
    <fa-icon [icon]="icons.video"></fa-icon>
  </p-button>
  <p-button title="Show output in console" (onClick)="logOutput()">
    <fa-icon [icon]="icons.console"></fa-icon>
  </p-button>
</div>

<p-popover #colInput>
  <div class="flex align-items-center gap-2">
    <div class="flex flex-column">
      <label for="columnInput">Columns to insert</label>
      <input
        type="text"
        id="columnInput"
        pInputText
        [(ngModel)]="columnNumber"
        class="w-10rem mb-4"
      />
      <p-slider
        [(ngModel)]="columnNumber"
        [min]="1"
        [max]="5"
        [step]="1"
        styleClass="w-10rem"
      />
    </div>
    <p-button label="Insert" (onClick)="addColumnSection()" />
  </div>
</p-popover>
